name: IaC Validation Workflow

on:
  push:
    branches:
    - main
    - development
  pull_request:
    branches:
    - main
    - development

jobs:
  terraform:
    name: Terraform Validation & Plan
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    # Step 3: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 4: Terraform Format & Validation
    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      run: terraform validate
